# Generated by Django 3.2.3 on 2021-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_category',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
    ]
